name: lensify
description: "Lensify - Professional OCR Scanner & PDF Generator"
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  
  # Image & Camera
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  image: ^4.1.7
  
  # OCR & ML
  google_mlkit_text_recognition: ^0.15.0
  flutter_tesseract_ocr: ^0.4.29
  google_mlkit_digital_ink_recognition: ^0.14.1
  
  # PDF & File Operations
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  
  # State Management & Storage
  shared_preferences: ^2.3.3
  provider: ^6.1.5
  crypto: ^3.0.3
  sqflite: ^2.3.3
  path: ^1.9.1
  
  # Monetization
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
